services:
  accounts :
    image: "chandunanepalli/accounts:v1"
    container_name: accounts-ms
    ports:
      - "9090:9090"
    deploy:
     resources:
      limits:
       memory: 700m
    networks:
     - chanduMS
  cards :
    image: "chandunanepalli/cards:v1"
    container_name: cards-ms
    ports:
      - "9091:9091"
    deploy:
     resources:
      limits:
       memory: 700m
    networks:
     - chanduMS	
  loans :
    image: "chandunanepalli/loans:v1"
    container_name: loans-ms
    ports:
      - "9092:9092"
    deploy:
     resources:
      limits:
       memory: 700m
    networks:
     - chanduMS  
networks:
  chanduMS:
   driver: "bridge"