spring:
  application:
    name: eurekaserver
  config:
    import: "optional:configserver:http://localhost:9000/"
    
management:
  endpoints:
    web:
      exposure:
        endpoints: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
      

