server:
  port: 9000
  
spring:
  application:
    name: "configserver"
  profiles:
    active: native #native git
  cloud:
    config:
      servers:
        native:
#          search-locations: "classpath:/config"
          search-locations: "file:///D://bankserver//config"
#        git:
#          uri: "https://github.com/eazybytes/eazybytes-config.git"
#          default-label: main
#          timeout: 5
#          clone-on-start: true
#          force-pull: true
          
encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"
